### ISSUE TITLE
[FEATURE REQUEST] Block the install of unsupported components/roles on arm64

### ISSUE THREAD

**Issue by seriva** [epiphany-platform/epiphany#2118] opened 2021-03-10 15:07 UTC
**Is your feature request related to a problem? Please describe.**
Currently we only support the x86_64 architectures but we need to add support for arm64.

**Describe the solution you'd like**
- We want the ability to block the install of unsupported roles on arm64 machines running CentOS. More information [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/arm/arm.md#artitecture-support-for-each-componentrole) and [here](https://github.com/epiphany-platform/epiphany/blob/develop/docs/design-docs/arm/arm.md#pre-flight-check).

Effected Ansible roles:
- all

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Extra info**
Design document and resources:
https://github.com/epiphany-platform/epiphany/tree/develop/docs/design-docs/arm

Terraform scripts for ARM hardware on AWS:
https://github.com/mkyc/aws-arm-simple-setup

---

**DoD checklist**

* [x] Changelog updated
* [x] COMPONENTS.md updated / doesn't need to be updated
* [ ] Feature has automated tests
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Idempotency tested
* [ ] Documentation added / updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Solution meets requirements and is done according to design doc
* [x] Usage compliant with license

**Comment by przemyslavic** [comment] 2021-04-16 12:43
@ar3ndt as far as I know, we do not support Ignite installation on arm machines yet.
I think that Ignite role should be removed from [here ](https://github.com/epiphany-platform/epiphany/pull/2156/files#diff-f103929a992efef8f98a45eeccb6483e5f6be8ea67731c9bb30d6d03c1b4db22R75) and from other distros.

The installation fails on task `download : Download file apache-ignite-2.9.1-bin.zip` as Ignite package is not being downloaded at all. It is commented out in the requirements.txt file and therefore not available in epirepo.
```
2021-04-16T11:32:11.4557541Z[38;21m11:32:11 INFO cli.engine.ansible.AnsibleCommand - TASK [download : Download file apache-ignite-2.9.1-bin.zip] ********************
2021-04-16T11:32:12.5777920Z[31;21m11:32:12 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Download file apache-ignite-2.9.1-bin.zip (3 retries left).
2021-04-16T11:32:15.5115299Z[31;21m11:32:15 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Download file apache-ignite-2.9.1-bin.zip (2 retries left).
2021-04-16T11:32:18.4268520Z[31;21m11:32:18 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Download file apache-ignite-2.9.1-bin.zip (1 retries left).
2021-04-16T11:32:21.3370020Z[31;21m11:32:21 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-54-78-134-216.eu-west-1.compute.amazonaws.com]: FAILED! => {"attempts": 3, "changed": false, "dest": "/tmp", "elapsed": 0, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "secontext": "system_u:object_r:tmp_t:s0", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "http://10.1.11.170/epirepo/files/apache-ignite-2.9.1-bin.zip"}
```

**Comment by przemyslavic** [comment] 2021-04-19 09:46
Fixed in #2221.

1. Please update the list of supported components as we are now able to install most of them including: logging, monitoring, postgresql, rabbitmq, kafka, zookeeper, ignite...
2. Add Vault to the list of unsupported components as it is not ready to install yet
3. The functionality doesn't work as expected, I was able to pass pre-flight checks with roles enabled such as logging, ignite, rabbitmq...

Moving back to TODO.

**Comment by przemyslavic** [comment] 2021-04-20 07:22
@ar3ndt it still doesn't work.
The problem is that Vault is disabled by default
```
---
kind: configuration/vault
title: Vault Config
name: default
specification:
  vault_enabled: false
```
but it still goes to inventory, causing it to fail on the preflight check even though I am not going to install this component.

```
2021-04-20T07:05:55.2164912Z[38;21m07:05:55 INFO cli.engine.ansible.AnsibleCommand - TASK [preflight : Check if components are supported by the architecture] *******
2021-04-20T07:05:55.2755180Z[31;21m07:05:55 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-xx-xxx-xxx-xx.eu-west-1.compute.amazonaws.com]: FAILED! => {
2021-04-20T07:05:55.2756734Z[38;21m07:05:55 INFO cli.engine.ansible.AnsibleCommand -     "assertion": "unsupported_components_checklist | length == 0",
2021-04-20T07:05:55.2757565Z[38;21m07:05:55 INFO cli.engine.ansible.AnsibleCommand -     "changed": false,
2021-04-20T07:05:55.2763598Z[38;21m07:05:55 INFO cli.engine.ansible.AnsibleCommand -     "evaluated_to": false,
2021-04-20T07:05:55.2770653Z[38;21m07:05:55 INFO cli.engine.ansible.AnsibleCommand -     "msg": "Your architecture aarch64 is not supported at CentOS by following components in inventory -> ['vault'].
```

Please verify the fix first before merging.

Moving back to TODO again.

**Comment by przemyslavic** [comment] 2021-04-29 07:04
Fixed.
✔️ Tested on CentOS aarch64 and Ubuntu/RHEL/CentOS x64.
As now all components are supported by arm, I manually added some items to the unsupported components list to check if the assertion is working properly.

**Comment by przemyslavic** [comment] 2021-04-29 11:05
✔️Tested again after #2265 with `elasticsearch-curator` enabled in feature-mapping.
```
021-04-29T10:59:14.9686532Z[31;21m10:59:14 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-1-1-1-1.eu-west-1.compute.amazonaws.com]: FAILED! => {
2021-04-29T10:59:14.9687636Z[38;21m10:59:14 INFO cli.engine.ansible.AnsibleCommand -     "assertion": "unsupported_components_checklist | length == 0",
2021-04-29T10:59:14.9696297Z[38;21m10:59:14 INFO cli.engine.ansible.AnsibleCommand -     "changed": false,
2021-04-29T10:59:14.9697597Z[38;21m10:59:14 INFO cli.engine.ansible.AnsibleCommand -     "evaluated_to": false,
2021-04-29T10:59:14.9699259Z[38;21m10:59:14 INFO cli.engine.ansible.AnsibleCommand -     "msg": "The following components in inventory are not supported for aarch64 architecture on CentOS OS: elasticsearch_curator. If the components are not neccessary, you may remove them from the feature-mapping (see https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md#how-to-create-custom-cluster-components)."
2021-04-29T10:59:14.9700550Z[38;21m10:59:14 INFO cli.engine.ansible.AnsibleCommand - }

```

**Closed as completed** 2021-05-04 07:59 UTC
Labels: type/feature-request, dependencies, area/development, area/ansible, priority/high
