### ISSUE TITLE
[BACKPORT][v1.1] Unable to add Grafana repository 

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2488] opened 2021-08-05 16:11 UTC
Source issue #2449
Pull request #2475

**Comment by przemyslavic** [comment] 2021-12-09 13:24
The issue is gone. I have successfully installed Grafana with epicli v1.1.0. We can just close this task and create a new one if it occurs again.

**Closed as completed** 2021-12-14 09:05 UTC
Labels: type/backport
