### ISSUE TITLE
[BUG] assert_no_postgres_nodes_number_change returning exception even if not changed value "count"

### ISSUE THREAD

**Issue by plirglo** [epiphany-platform/epiphany#2737] opened 2021-11-04 13:42 UTC
**Describe the bug**
In specified condition ```epicli apply``` failed with exception: "Postgresql scaling is not supported yet. Please revert your 'postgresql' count to previous value." even if no configuration changes have been done.

Review assert_no_postgres_nodes_number_change function to fix bug 

**How to reproduce**
1. execute `epicli apply -f config.yml` twice

**Expected behavior**
Scripts should pass all assetions since no changes have been done

**Config files**
Problem occurs when specified configuration is used:

```yaml
specification:
  components:
        kubernetes_master:
          count: 1
        postgresql:
          count: 0
---
kind: configuration/feature-mapping
title: Feature mapping to roles
name: default
specification:
  roles_mapping:
    kubernetes_master:
    - kubernetes-master
    - helm
    - applications
    - node-exporter
    - filebeat
    - firewall
    - vault
    - postgresql
...
```

**Environment**
- Cloud provider:  All
- OS: All

**epicli version**: 1.2.0

**Additional context:**
Comparison uses values from inventory and configuration files. In this specified configuration values don't meet.

---

**DoD checklist**

* [x] Changelog updated (if affected version was released)
* [x] COMPONENTS.md updated / doesn't need to be updated
* [x] Automated tests passed (QA pipelines)
  * [x] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [x] Idempotency tested
* [x] Documentation updated / doesn't need to be updated
* [x] All conversations in PR resolved
* [x] Backport tasks created / doesn't need to be backported

**Comment by przemyslavic** [comment] 2021-11-04 15:28
It also fails if the configuration is reapplied for a single machine installation.

The problem is that the number of PostgreSQL nodes in inventory and in the configuration file are compared and 
for single machine installation, after first apply, we have 1 PostgreSQL host in inventory, but in configuration yaml PostgreSQl component is set to 0. This causes that installation fails on second apply as the numbers are different.

**Comment by przemyslavic** [comment] 2021-12-28 09:25
Tested by @atsikham https://github.com/epiphany-platform/epiphany/pull/2811#issuecomment-1000235627.
Moving to DoD.

**Closed as completed** 2021-12-28 10:09 UTC
Labels: type/bug
