### ISSUE TITLE
[BUG][Logging] Frequent fails of 'kibana : Wait for kibana to be ready' step

### ISSUE THREAD

**Issue by atsikham** [epiphany-platform/epiphany#1575] opened 2020-08-21 06:57 UTC
**Describe the bug**
This bug is the result of #1497 spike.
According to [documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/DATABASES.md#how-to-start-working-with-opendistro-for-elasticsearch) and feature-mapping `kibana` role can be used in `logging` and `opendistro_for_elasticsearch` components. Usually It's ok to deploy 1-2 instances of these components without an error, but it frequently fails on `kibana : Wait for kibana to be ready` step when trying to scale up with greater number of instances.

**To Reproduce**
1. deploy 1 `logging` instance 
2. edit config file to scale up, `count: 3`
3. apply new configuration

**Expected behavior**
- Kibana and all other components are up, there are no any errors during deployment.
- **[Documentation](https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/CLUSTER.md) about scaling process should be updated.**

**Config files**
feature-mapping.yml
```
---
...
specification:
  roles_mapping:
    logging:
      - logging
      - kibana
      - node-exporter
      - filebeat
      - firewall
    opendistro_for_elasticsearch:
      - opendistro-for-elasticsearch
      - node-exporter
      - filebeat
      - firewall
      - kibana
...
```

**Cloud Environment (please complete the following information):**
Azure, AWS.

**Additional context**
Found in version 0.7.1.

**More details**
```
8:51:02 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (3 retries left).
08:51:05 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (3 retries left).
08:51:09 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (2 retries left).
08:51:11 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (2 retries left).
08:51:15 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (1 retries left).
08:51:18 ERROR cli.engine.ansible.AnsibleCommand - FAILED - RETRYING: Wait for kibana to be ready (1 retries left).
08:51:22 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-18-184-144-226.eu-central-1.compute.amazonaws.com]: FAILED! => {"attempts": 60, "cache_control": "no-cache", "changed": false, "connection": "close", "content": "Kibana server is not ready yet", "content_length": "30", "content_type": "text/html; charset=utf-8", "date": "Thu, 20 Aug 2020 08:51:21 GMT", "elapsed": 0, "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "retry_after": "30", "status": 503, "url": "http://10.1.3.147:5601/api/kibana/settings"}
08:51:24 ERROR cli.engine.ansible.AnsibleCommand - fatal: [ec2-35-157-40-252.eu-central-1.compute.amazonaws.com]: FAILED! => {"attempts": 60, "cache_control": "private, no-cache, no-store, must-revalidate", "changed": false, "connection": "close", "content": "Kibana server is not ready yet", "content_length": "30", "content_type": "text/html; charset=utf-8", "date": "Thu, 20 Aug 2020 08:51:24 GMT", "elapsed": 0, "msg": "Status code was 503 and not [200]: HTTP Error 503: Service Unavailable", "redirected": false, "retry_after": "30", "status": 503, "url": "http://10.1.3.66:5601/api/kibana/settings"}
```

**Comment by rpudlowski93** [comment] 2020-08-28 08:10
The same problem has been observed here: [link](https://app.zenhub.com/workspaces/epiphany-platform-5ef9d3c749afc20019782391/issues/epiphany-platform/epiphany/1497)

**Comment by atsikham** [comment] 2020-08-28 14:21
@rpudlowski93 Azure, this information is already in description.

**Comment by rafzei** [comment] 2021-06-24 11:55
Looks like we fix this issue by upgrading ODFE [PR 1772](https://github.com/epiphany-platform/epiphany/pull/1772)
Confirmed by @przemyslavic that the issue is not occurring anymore (tested scenario: 1->2 & 2->3).
I'm closing it. If you face it again, please reopen and send us details.

**Closed by rafzei** 2021-06-24 11:55 UTC
Labels: area/logs, provider/azure, type/bug
