### ISSUE TITLE
Upgrade Ubuntu/Redhat base image

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1162] opened 2020-04-15 08:54 UTC

**Comment by przemyslavic** [comment] 2020-06-16 11:56
A duplicate of task [#1330 ](https://github.com/epiphany-platform/epiphany/issues/1330)
Done in [#1357 ](https://github.com/epiphany-platform/epiphany/pull/1357/files)

**Closed** 2020-06-16 11:56 UTC
