### ISSUE TITLE
[Spike] Verify if "disks are not removed during downscale" for AWS as well

### ISSUE THREAD

**Issue by sk4zuzu** [epiphany-platform/epiphany#1590] opened 2020-08-28 08:24 UTC
Please take a look at #1574. We need to verify if the problem exists in AWS as well and create proper bug report when needed. :+1:

**Comment by mum0l** [comment] 2020-09-18 14:56
Tested on 2 different deployments (ubuntu+redhat) in AWS, and this issue doesn't exist - disks are properly removed. Taking this into account, I suggest we can close this issue.

**Comment by mkyc** [comment] 2020-10-06 15:04
@mum0l what is output of this task?

**Comment by mkyc** [comment] 2020-11-03 15:59
It looks like I missed some comment from @mum0l and it should be just verified and moved to DoD.

**Comment by mum0l** [comment] 2020-11-04 05:13
Unfortunatelly I cannot reproduce it now. What I did was simply downscale the app, and looked into gui + CLI if disks are removed.

**Comment by ar3ndt** [comment] 2020-11-05 08:44
Disks are removed properly during downscale.

**Closed** 2020-11-05 09:03 UTC
Labels: provider/aws, type/spike
