### ISSUE TITLE
[BUG] Failed epicli apply can lead to broken repository machine (disabled system repos)

### ISSUE THREAD

**Issue by ks4225** [epiphany-platform/epiphany#2324] opened 2021-05-13 12:56 UTC
**Describe the bug**
If epicli fails in a state where the repository machine has disabled system repos, subsequent epicli applies will not be able to recover.

e.g. keep failing because firewalld package will not be found

**How to reproduce**
1. No specific step here, but sometimes epicli will fail
2. Try to re-run epicli

**Expected behavior**
Perhaps epicli could detect when system repos are disabled at the start of its processing. If it detects that system repos are disabled, re-enable them before trying to download packages.

**Config files**
If applicable, add config files to help explain your problem.

**Environment**
- Cloud provider: Azure
- OS: Ubuntu 18.04.4 LTS

**epicli version**: 1.0.0

**Additional context**

---

**DoD checklist**

* [ ] Changelog updated (if affected version was released)
* [ ] COMPONENTS.md updated / doesn't need to be updated
* [ ] Automated tests passed (QA pipelines)
  * [ ] apply
  * [ ] upgrade
* [ ] Case covered by automated test (if possible)
* [ ] Idempotency tested
* [ ] Documentation updated / doesn't need to be updated
* [ ] All conversations in PR resolved
* [ ] Backport tasks created / doesn't need to be backported

**Comment by rafzei** [comment] 2021-06-21 08:43
Thanks for reporting the problem @ks4225. Due to our current workload, we estimated the solution to be implemented in version 1.2.0, but in order not to leave you alone, we also created issue #2388 to document some manual steps.

**Comment by to-bar** [comment] 2021-06-25 15:50
@ks4225 I checked our logic and for Ubuntu we already have the following code in `download-requirements.sh` to avoid such an issue: 
```
repos_backup_file="/tmp/epi-repository-setup-scripts/enable-system-repos.sh"
# restore system repositories in case they're missing if ansible role gets interrupted
if [[ ! -f /etc/apt/sources.list ]]; then
    if [[ -f /var/tmp/enabled-system-repos.tar ]] && [[ -f ${repos_backup_file} ]]; then
        echol "OS repositories seems missing, restoring..."
        ${repos_backup_file}
    else
        echol "/etc/apt/sources.list seems missing, you either know what you're doing or you need to fix your repositories"
    fi
fi
```

And I tested two cases:

1)
- abort on `common` role - the first one after `repository`,
- remove flag file `/tmp/epi-download-requirements/download-requirements-done.flag`, which by default expires after 2 hours since creation time, to not skip `download-requirements.sh` on re-rerun,
- check log from download-requirements.sh (2nd line):
```
root@repository:~# grep -B1 -A1 "OS repositories seems missing" /tmp/epi-download-requirements/log
Docker platform: linux/amd64
OS repositories seems missing, restoring...
Dependency list: /tmp/epi-download-requirements/.dependencies
```
2)
- abort on `common` role,
- this time `repository : Download Epiphany requirements` task was skipped (due to valid flag file)
- but `epirepo` is still available and packages required by Epiphany are there, so I was able to install `firewalld`.

Do you use `firewalld` on Ubuntu? We have a [known issue with it](https://github.com/epiphany-platform/epiphany/issues/849) so it's disabled by default (`install_firewalld: false`) and we do not test it.

To reproduce this issue I would need more details - like non-default settings in config manifest, on which task `epicli` failed for the first run, on which for re-apply, error message from the failure and whether `repository : Download Epiphany requirements` task was skipped.

So please provide more details when you encounter such an issue again in order to help us to reproduce it.

We have added new doc regarding repository: https://github.com/epiphany-platform/epiphany/blob/develop/docs/home/howto/REPOSITORY.md

**Comment by ks4225** [comment] 2021-07-08 10:32
Yes, I do remember seeing the logic for this scenario when doing our own debugging. I will let you know if I do have a clearer scenario that reproduces this issue.

We don't use `filewalld`.

The documentation looks good, it definitely works as a workaround for this situation.

**Comment by erzetpe** [comment] 2021-07-13 12:33
Returning to analysis as it hasn't been reproduced and we need more data to reproduce this bug.

**Comment by erzetpe** [comment] 2021-08-16 08:51
@ks4225: We are closing this issue as we weren't able to reproduce this. If you still have this issue please reopen this issue and we will try to help.

**Closed as completed by erzetpe** 2021-08-16 08:51 UTC
Labels: type/bug, source/community
