### ISSUE TITLE
[BUG] High CPU load on Kafka

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1414] opened 2020-07-03 04:22 UTC
**Describe the bug**
> Using Epiph 0.5x with 3 kafka nodes and running DE 1.2 we see high cpu load on all three Kafka nodes even if no activity.  

**To Reproduce**
- Create a new Epiphany cluster 
- Even with no traffic, Kafka shows high CPU usage

**OS (please complete the following information):**
 - OS: Ubuntu

**Cloud Environment (please complete the following information):**
 - Cloud Provider: MS Azure

**Epiphany version:**
0.5.x

**Context:** 
Epiphany Cluster with 3 Kafka nodes and 10 Kubernetes nodes

** VM Size** 
DS2v2 (2 CPU, 7GB RAM)

**Comment by seriva** [comment] 2020-07-03 06:47
We saw that on DEConnect as well. 1 Kafka node which seemingly was busy without any load on it. Intermittently every few seconds 40 to 60 percent CPU load spikes.

Not confirmed but most likely the Java garbage collector kicking in every few seconds to cleanup something. Bumping the memory from 2 to 4 GB on the node seemed to resolve the situation.

**Comment by toszo** [comment] 2020-07-03 08:51
Asked questions to the original creator of this issue. Waiting for response.

**Comment by toszo** [comment] 2020-07-06 06:44
Received a response and updated description. 
From what @seriva suggested it could be first thing to check - JVM settings (bump from 2GB to 4 RAM). 

The next thing is Kafka exporter - check if it does not consume memory due to some bug.

**Comment by toszo** [comment] 2020-07-09 18:21
Got this message from one of the apps: 
> Due to the high CPU usage – Kafka metrics exporter caused the system to 
> become unstable and was turned off – that has been turned back since we scaled
> up the CPUs.

**Comment by seriva** [comment] 2020-07-16 08:01
So far I have been not able to reproduce this. Created a cluster with 2 Kafka nodes, added 25 different topics where I pushed about 6 million messages with 25 producers, reading them with the same amount of consumers. Also added some 30 streams using the subscription-processor we created for another project. CPU usage on both nodes are around 50% to 70% which would be expected for the load. After shutting down a majority of the producers/consumers and streams the load went down without unusual spikes in CPU usage.

**Comment by seriva** [comment] 2020-07-30 06:05
So for on a new cluster we have not seen this issue. All clusters reporting this had a bunch of topics/streams running on them. The fact that no data is ingested or moved does not mean Kafka will sit idle. Various processes like transactions, data replication, overhead from subscribed consumers and producers might cause overhead. For now I suggest to close this.

**Closed** 2020-08-04 09:09 UTC
Labels: area/kafka, type/bug
