### ISSUE TITLE
[BACKPORT][v0.9] Unable to add Grafana repository

### ISSUE THREAD

**Issue by to-bar** [epiphany-platform/epiphany#2490] opened 2021-08-05 16:34 UTC
Source issue #2449
Pull request #2475

**Comment by przemyslavic** [comment] 2021-12-09 14:14
The issue is gone. I have successfully installed Grafana with epicli v0.9.2 We can just close this task and create a new one if it occurs again.

**Closed as completed** 2021-12-14 09:05 UTC
Labels: type/backport
