### ISSUE TITLE
Add Helm charts offline repository and make possible to install charts from it (internal repo)

### ISSUE THREAD

**Issue by erzetpe** [epiphany-platform/epiphany#1189] opened 2020-04-23 12:10 UTC

**Comment by ar3ndt** [comment] 2020-04-30 11:01
Helm charts are stored in `roles/repository/files/server/charts` path
During repository role they are served within apache repo server.
It is required to add charts there in order to be automatically installed by separate helm role.

**Comment by ar3ndt** [comment] 2020-07-01 08:34
Update:

Helm charts are stored in `roles/helm_charts/files/system` path
In repository role Helm charts are added to apache repo server. Repo task archives all charts from the mentioned path (`.tgz`) and serve them.
Installation of particular Helm charts is not performed here -> each particular role that needs to install Helm chart has to trigger separate single helm chart installation task -> `roles/helm/tasks/install-chart.yml`

**Comment by sk4zuzu** [comment] 2020-07-09 10:59
The current implementation in the helm / helm_charts / repository ansible roles deploys only the "system" chart repo (served from Apache2 as a part of our standard repository) and I believe it has been designed only for internal usage, i.e. from other roles inside the Epiphany ansible __>>> source code <<<__.

To add a new "system" type chart to the repo (by design) one needs to put the whole uncompressed source code of that chart inside the `roles/helm_charts/files/system` folder inside the Epiphany source code tree and then execute `epici apply ...` to copy it to the destination repository instance in the cluster at hand and only after that chart can be installed in Kubernetes.

IMO, there are two crucial things that we have to consider if we want to have a working solution for the offline helm chart repo:
1. Publicly available charts usually use publicly available docker images as basis for the containers in Kubernetes pods.
2. Any Helm chart can have multiple dependencies (defined inside the `requirements.yaml` and `requirements.lock` files)l. So it will happen for sure that for some charts we create, we will get multiple dependecies that in turn have multiple other dependecies and so on...

I think that for the case of the "system"  charts it can be done manually by a person that creates the chart  (Epiphany member/developer). So in this case, that person will be responsible for adding all needed docker images, adding all required charts and modifying default configs of the charts included as dependencies (for example docker image urls to point to the offlice image registry we provide internally). __This exact approach has been used in the Vault MVP code.__

So that was the introduction, now some questions :).
1. What will we do with the "user" chart repo that we skipped during the initial implementation? Will we support the "user" repo in the end?
2. What kind of interface will we provide to the users, so they can deploy a chart and include it in their oflfine package and running offline repository (with all kinds of dependencies mentioned above)?
3. Shouldn't we implement some automated logic that would collect all dependecies (mentioned above) so the implementer (user or member) would not have to do it manually?

@ar3ndt @erzetpe any thoughts? I believe without answering those questions we can't move forward. :)

**Comment by ar3ndt** [comment] 2020-07-09 13:02
AD1. Yeah I think user repo will need some additional "options" via epi client but I think it needs discussion with wider audience about the needs.
AD2. epicli dedicated tasks?
AD3. In this approach we should then change the behavious for all the packages and images in epiphanny as well which makes this task out of the scope IMO

**Comment by sk4zuzu** [comment] 2020-07-09 13:32
Then maybe I'd suggest narrowing scope of this task only to the "system" related repo, changing the title of the issue (so it says it's "system" related), and maybe creation of additional issues about the "user" related improvements for the future? 🤔

**Comment by sk4zuzu** [comment] 2020-10-06 08:34
> Update:
> 
> Helm charts are stored in `roles/helm_charts/files/system` path
> In repository role Helm charts are added to apache repo server. Repo task archives all charts from the mentioned path (`.tgz`) and serve them.
> Installation of particular Helm charts is not performed here -> each particular role that needs to install Helm chart has to trigger separate single helm chart installation task -> `roles/helm/tasks/install-chart.yml`

Judging from this comment and from the title of the issue `Add offline repository creation for helm charts and installation of helm charts from local repository` this feature is actually currently implemented for the "system" repo. :female_detective: 

1. Is the above statement correct? :thinking: 
2. Can we change the title so it includes "system repo" and close the issue? :thinking: 

@ar3ndt @erzetpe

**Comment by to-bar** [comment] 2020-10-16 11:26
Renamed task title while grooming it.

**Closed** 2020-10-20 09:24 UTC
Labels: area/kubernetes, size/XS, type/feature-request
